services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
      PYTHON_API_URL: ${PYTHON_API_URL:-http://127.0.0.1:5000}
      PYTHON_API_KEY: ${PYTHON_API_KEY:-test}
    restart: always
