version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: nginx -g 'daemon off;'

  # Ajoutez d'autres services ici si nécessaire (comme une base de données, etc.)
