name: Copier le Repository Complet

on: push

jobs:
  copy-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABB7Krv7xk
vEoTNdFWJ2FQrfAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIEljYBhZKQ1a90eH
q7T6f/SOq3SQX7A8Nsr+cplR5hfNAAAAoDrPeuZGaHnPnjS9egItzGEc59MtUDh6H45UAN
bHVUXjwyZz5OuYCeBvN095OwDIVxIMa8iHU5hIqf9n1cB/BRLbYilywgGV7L56KOCbwLxi
0H6K4YnHJe0mfuQNDeFxXczTxAtzelZKpnLEabf1pfiZuw2WF2yi0ETOxSclnRmr0Pzik+
MZxhyIljsO2qVK6zEuh2G4WpQ1/F/dZBvshrs=
-----END OPENSSH PRIVATE KEY-----
" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Cloner le dépôt distant et pousser les changements
      run: |
        # Cloner le dépôt distant via SSH
        git clone git@github.com:EpitechMscProPromo2025/T-WEB-700-LIL_9.git temp_repo
        # Copier les fichiers, sauf .github/workflows
        rsync -av --exclude '.github/workflows/' . temp_repo/
        # Pousser les changements
        cd temp_repo
        git add .
        COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        git commit -m "${COMMIT_MESSAGE}"
        git push origin main

    - name: Cleanup SSH
      if: always()
      run: rm -f ~/.ssh/id_rsa
