name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Execute SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd bnclike_front
          git pull origin main
          docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker rmi countofmoney
          docker build -t countofmoney .
          docker run -d -p 8080:80 --name web-client countofmoney
