name: Copier le Repository Complet dans le sous-dossier /web

on: push

jobs:
  copy-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Cloner le dépôt distant
      run: git clone git@github.com:EpitechMscProPromo2025/T-WEB-700-LIL_9.git temp_repo

    - name: Copier le code source dans le sous-dossier /web du dépôt distant
      run: |
        # Créer un sous-dossier /web s'il n'existe pas
        mkdir -p temp_repo/web
        # Copier tout sauf le dossier .git et .github/workflows dans le sous-dossier /web
        rsync -av --exclude '.git' --exclude '.github/workflows/' . temp_repo/web/

    - name: Configurer l'utilisateur Git
      run: |
        git config --global user.email "camille.lecoq@epitech.eu"
        git config --global user.name "Dinoozz"

    - name: Commit et Push les changements
      run: |
        cd temp_repo
        git add web
        COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        cat ${COMMIT_MESSAGE}
        git commit -m "Mise à jour du sous-dossier /web: ${COMMIT_MESSAGE}"
        git push origin main

    - name: Cleanup SSH
      if: always()
      run: rm -f ~/.ssh/id_rsa
